### ISSUE TITLE
Angular?

### ISSUE THREAD

**Issue by justincy** [rootsdev/familysearch-reference-client#1]
It looks like this is setup to be a single page app with angular. Is that correct? If so, I must not understand the purpose of this project.

The biggest potential for a project like this is to generate a framework of embeddable widgets that can easily be dropped into any environment that runs HTML and JavaScript (web or mobile, primarily). With that, you could easily get a single page app by connecting all the widgets.

I am concerned that developing with angular only satisfies the single page app objective and not the embeddable scenario. I admit I don't know enough about angular, but what little I do know tells me it's not as easy to just drop in anywhere.

So is the purpose of the project just to create a single page app? What is the vision for the utility of the single page app? Will it be extensible and configurable?

**Comment by DallanQ** [comment]
If you want embeddable widgets using jquery, check out familysearch-widgets. I believe Dovy is accepting pull requests for that.

This project also has embeddable widgets, but the widgets are written using angular, not jquery - mainly because I can't conceive writing a large app like FamilySearch completely in jQuery. Large-scale apps now-days tend to be written using some sort of MVC framework. I prefer angular. And since this is just javascript + html, it will run on mobile, and you can embed these widgets in any html page, even one generated by a back-end server, contains jquery, etc.

Ultimately I believe these things should be written using Web Components: http://css-tricks.com/modular-future-web-components/ However, I don't believe Web Components are ready for prime-time. In the meantime, using components written using angular is a pretty decent alternative.

For example, here are a few components I'm working on. The person view template is currently:

```
<div fs-person-profile></div>
<div class="mainContent">
  <div class="row">
    <div class="col-md-9">
      <div fs-life-sketch-section state="lifeSketchState"></div>
      <div fs-person-vital-facts-section state="vitalFactsState"></div>
      <div fs-person-other-facts-section state="otherFactsState"></div>
      <div fs-notes-section state="notesState"></div>
    </div>
  </div>
</div>
```

which means it's composed of components for a person profile, life sketch, vitals, other facts, and notes. (Other sections to come.) Drilling down, the fs-person-vital-facts-section template is:

```
<div class="vitalsWidgetContainer">
  <div fs-section section-title="Vital Information" state="state" details-openable="true" items="vitals">
    <div class="panel-body vitalsBody">
      <div fs-name item="vitals['name']"></div>
      <div fs-gender item="vitals['gender']"></div>
      <div fs-fact item="vitals['birth']"></div>
      <div fs-fact item="vitals['christening']"></div>
      <div fs-fact item="vitals['death']"></div>
      <div fs-fact item="vitals['burial']"></div>
    </div>
  </div>
</div>
```

Which means it has a fs-section component for handling section opening/closing, and contains name, gender, and fact components. The fs-fact template is:

```
<div fs-item item="item" editable="true" deletable="true">
  <div fs-fact-summary item="item" type="{{getDisplayType(item)}}" ng-hide="item._isEditing()"></div>
  <div fs-item-details item="item" ng-show="item._isOpen()"></div>
  <div fs-fact-edit item="item" type="{{getDisplayType(item)}}" ng-show="item._isEditing()" save="save()"></div>
</div>
```

and finally, the fs-fact-summary template is:

```
<div fs-item-summary label="{{type}}" item="item">
  <span class="eventDate">17 March 1971</span><br/>
  <span class="eventLocation">Chicago, Cook, Illinois, United States</span>
</div>
```

Each component is like a "module" that contains an html template, javascript, and eventually css. Think of a component like a function that has a well-defined set of parameters you need to pass into it but which takes care of handling its own display and behavior. It's self-contained. You can include either high-level or low-level components onto your own web-page, so long as you 
1. include the angular javascript and bootstrap css and a few other files at the top of the page, 
2. enclose the components you want to inside a div that contains an "ng-app" attribute, which tells angular to pay attention to the stuff inside the div,
3. write a small angular controller to grab the data for the component from FamilySearch (or a global javascript object that you've already populated) and pass it into the component (e.g., the fs-fact component needs to have a fact passed in).

I will eventually provide an example showing how to use the SDK to fetch a person from FamilySearch and pass the birth fact into an fs-fact component that will display the birth info and allow users to edit it. It will be about 20 lines of javascript.

It's a bit of a learning curve. If you don't want to climb it, feel free to use familysearch-widgets. In my opinion though, it's worth the climb.

**Comment by justincy** [comment]
I didn't know that angular can be embedded like that. It uses the URL hash, right? Or can it be configured to not do that?

**Comment by DallanQ** [comment]
btw, 90% of the javascript code for this project will be in the re-usable components. The primary benefits of angular are it handles two-way binding between the model and the view (template), and it makes it easy to compose components.

**Comment by DallanQ** [comment]
Angular has a lot of different parts. The part that handles URL routing is the "router". A complete app would use the router, but you don't have to use it.  All you really need is something like:

```
<body>
   ...
  <div ng-app> <!-- all angular stuff goes in here; you can put ng-app on your body tag if you want -->
    <div ng-controller="MyController"> <!-- controller javascript populates myFact -->
      <div fs-fact item="myFact"></div> <!-- myFact is passed into the fs-fact component -->
   </div>
  </div>
  ...
</body>
```

You'll be able to put that code snippet on any page you want. The controller script would look something like:

```
angular.module('MyModule').controller('MyController', function($scope) {
  $scope.myFact = ...
});
```

**Comment by justincy** [comment]
Cool. I feel better about that.

**Comment by DallanQ** [comment]
I added a simple example showing how to use the components outside of AngularJS. It's described at the bottom of the readme.

**Comment by justincy** [comment]
That example has a lot of javascript dependencies. I'd like to use the person card popup in a project of mine but I would prefer not to include so many other things too. Are they all necessary?

**Comment by dovy** [comment]
You could use the CSS from the widgets repo and just use jquery (boostrap) popover.  :)
